### ISSUE TITLE
Interactable example in `Doc.BindView`

### ISSUE THREAD

**Issue by EduardoLR10** [dotnet-websharper/docs#28]
In [this](https://developers.websharper.com/docs/v4.x/fs/ui) section of the documentation, subsection `Inserting Views in the Doc`, the following code is presented to exemplify `Doc.BindView`:
```fsharp
let varTxt = Var.Create ""
let vWords =
    varTxt.View
    |> View.Map (fun s -> s.Split(' '))
    |> Doc.BindView (fun words ->
        words
        |> Array.map (fun w -> li [] [text w] :> Doc)
        |> Doc.Concat
    )
div [] [
    text "You entered the following words:"
    ul [] [ vWords ]
]
```
Although correct, the above code forces the reader to change the content of the `Var` for the text in the code itself in order to see the splitting effect in the browser. My suggestion is to change the example to this:
```fsharp
let varTxt = Var.Create ""
let vWords =
    varTxt.View
    |> View.Map (fun s -> s.Split(' '))
    |> Doc.BindView (fun words ->
        words
        |> Array.map (fun w -> li [] [text w])
        |> Doc.Concat
    )
div [] [
    Doc.InputType.Text [] varTxt
    text "You entered the following words:"
    ul [] [ vWords ]
]
```
In this manner, the reader will be able to interact with the text via the browser and immediately see the reactivity system working as intended (notice also the removal of the `:> Doc` that at version 6.x throws a warning). If this option is not the best, we could put some initial text in `varTxt` to generate some list items on the web page for the reader. Can I improve this? Which approach should I go for? I personally think the one with the interactable text box is the best option.

**Comment by granicz** [comment]
Yeah, that's a reasonable change, easier for the user, so better. I believe the original intention was to build on the example preceding it:

```fsharp
let varTxt = Var.Create ""
let vLength =
    varTxt.View
    |> View.Map String.length
    |> View.Map (fun l -> sprintf "You entered %i characters." l)
div [] [
    Doc.Input [] varName
    textView vLength
]
```

... which does provide a text box as the input for the computed reactive view. Incidentally, this example has a typo, the text box should reference `varTxt` and not `varName`.

All in all, can you submit a PR for what you suggest (and the fix above)? Thanks!

**Comment by granicz** [comment]
Sorry, just saw #27 for the typo I mentioned above. We could close both issues with a single PR.

**Comment by EduardoLR10** [comment]
I will submit a PR with both changes shortly.
